import { Header } from '@/components/Header'
import './globals.css'
import { Footer } from '@/components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* コンテンツが少ない場合もフッターは一番下に配置する */}
      <body
        className="flex flex-col min-h-screen"
      >
        <Header />
        <main
          className="flex-grow"
        >
        {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
